title: 5 LOAVES & 2 FISHES GALLERY # your name (or website title) here
logo: "images/5-loaves-2-fish.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seeing God's fingerprints on my projects =)
  <br><br>
  We don't need many ideas, we only need God's ideas.
  <br><br>
  The Bible Verses that walked me through this programme: JOSHUA14:12 / NEH8:10
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
